apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-demo-deployment
spec:
  selector:
    matchLabels:
      app: pvc-demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pvc-demo
    spec:
      containers:
      - name: pvc-demo
        image: piyushtrainingacr.azurecr.io/demo/pvcdemo:v1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: www-persistent-storage
            mountPath: /data
    volumes:
      - name: www-persistent-storage
        persistentVolumeClaim:
          claimName: demo-pvc

