apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
  labels:
    app: pvc-demo
    tier: backend
spec:
  containers:
  - name: pvc-demo
    image: piyushtrainingacr.azurecr.io/demo/pvcdemo:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
