apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
stringData:
  azurestorageaccountname: piyushtrainingstorage
  azurestorageaccountkey: 7Udd4yga8cNMi722Mno4nvPKmiQY1W7yt6Gd9P4YPttUKXyKRwAgDETKFwC/MA0chB6r+I/3viqvfNybAolxCQ==