apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.pod.name }}"
  namespace: "{{ .Values.namespace.name }}"
  labels:
    app: "{{ .Values.pod.name }}"
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-definition.yaml") . | sha256sum }}
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  containers:
  - name: "{{ .Values.pod.container.name }}"
    image: "{{ .Values.pod.container.registry }}/{{ .Values.pod.container.repository }}:{{ .Values.pod.container.tag }}"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: SPRING_APPLICATION_NAME
        valueFrom:
          configMapKeyRef:
            name: "{{ .Values.configmap.name }}"
            key: spring.application.name
      - name: SPRING_APPLICATION_ENV
        valueFrom:
          configMapKeyRef:
            name: "{{ .Values.configmap.name }}"
            key: spring.application.env


