apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  namespace: "{{ .Values.namespace.name }}"
  labels:
    app: "{{ .Values.service.name }}"
spec:
  ports:
  - port: 80
    targetPort: 8080  
    name: http
  selector:
    app: "{{ .Values.pod.name }}"
  type: "{{ .Values.service.type }}"