apiVersion: v1
kind: PersistentVolume
metadata:
  name: demoapp-pv
  
spec:
  capacity:
    storage: 0.3Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: para-sara
    shareName: tempfiles
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl