apiVersion: v1
kind: Service
metadata:
  name: demopvc-svc
  labels:
    app: demopvc-svc
spec:
  ports:
  - port: 80
    targetPort: 8080  
    name: http
  selector:
    app: demopvc-pod
  type: LoadBalancer