apiVersion: v1
kind: Service
metadata:
  name: demoapp-service 
  labels:
    app: nodeapp-svc
spec:
  ports:
  - port: 80
    targetPort: 8080  
    name: http
  selector:
    app: nodeapp-deploy
  type: LoadBalancer
