apiVersion: v1
kind: Service
metadata:
  name: paraapp-service
  labels:
    app: paraapp-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: paraapp-deployment
  type: LoadBalancer
