---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-headless
  labels:
    app: demoapp-sts
spec:
  ports:
  - name: demoapp-headless
    port: 80
  clusterIP: None
  selector:
    app: demoapp-sts