---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demoapp-sts
  labels:
    app: demoapp-sts
spec:
  replicas: 4
  serviceName: demoapp-headless
  selector:
    matchLabels:
      app: demoapp-sts
  template:
    metadata:
      labels:
        app: demoapp-sts
    spec:
      containers:
        - name: demoapp-sts
          image: piyushtrainingacr.azurecr.io/manulife/pvcdemo:v1
          ports:
          - containerPort: 80
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: spring.application.name
            - name: SPRING_APPLICATION_ENV
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: spring.application.env
          volumeMounts:
            - name: data
              mountPath: /mnt/azure
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: demopvc-storageclass
        resources:
          requests:
            storage: 1Gi

          