apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-definition.yaml") . | sha256sum }}
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.deployment.name }}"
  replicas: "{{ .Values.deployment.replicas }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.name }}"
    spec:
      containers:
      - name: "{{ .Values.deployment.container.name }}"
        image: "{{ .Values.deployment.container.registry }}/{{ .Values.deployment.container.repository }}:{{ .Values.deployment.container.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.configmap.name }}"
                key: spring.application.name
          - name: SPRING_APPLICATION_ENV
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.configmap.name }}"
                key: spring.application.env
