apiVersion: v1
kind: Pod
metadata:
  name: demopvc-pod-sc
  labels:
    app: demopvc-pod-sc
    tier: backend
spec:
  containers:
  - name: demopvc-pod-sac
    image: piyushtrainingacr.azurecr.io/manulife/pvcdemo:v1
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: SPRING_APPLICATION_NAME
        valueFrom:
          configMapKeyRef:
            name: demopvc-config
            key: spring.application.name
      - name: PVC_MOUNT_PATH
        valueFrom:
          configMapKeyRef:
            name: demopvc-config
            key: pvc.mount-path
    volumeMounts:
      - name: demoapp-pvc-claim
        mountPath: /mnt/azure
  volumes:
    - name: demoapp-pvc-claim
      persistentVolumeClaim:
        claimName: demoapp-pvc-sc